# Opentelemtry Agent Config
extensions:
  health_check:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:13133"
receivers:
  hostmetrics:
    scrapers:
      cpu:
      memory:
      network:
      # System load average metrics https://en.wikipedia.org/wiki/Load_(computing)
      load:
      disk:
      filesystem:
      # Paging/Swap space utilization and I/O metrics
      paging:
      # Aggregated system process count metrics
      processes:
      # System processes metrics, disabled by default
      process:
exporters:
  signalfx:
    access_token: ${SPLUNK_ACCESS_TOKEN} 
    realm: ${SPLUNK_REALM} 
    ingest_url: ${SPLUNK_INGEST_URL} 
    trace_url: ${SPLUNK_TRACE_URL} 
    api_url: ${SPLUNK_API_URL}

processors:
  resource/splunk_at_splunk: # Adds attributes to metrics
    attributes:
      - action: insert
        key: splunkit/team
        value: ${SPLUNK_TEAM}
      - action: insert
        key: splunkit/resource
        value: ${RESOURCE_TYPE}
  batch:
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true

service:
  telemetry:
    metrics:
      address: "${SPLUNK_LISTEN_INTERFACE}:8888"
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch, resourcedetection, resource/splunk_at_splunk]
      exporters: [signalfx]
