# Opentelemtry Agent Config
receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      # System load average metrics https://en.wikipedia.org/wiki/Load_(computing)
      load:
      # Paging/Swap space utilization and I/O metrics
      paging:
      # Aggregated system process count metrics (not working 'No process information is available for this host.')
      processes:
      # Per process CPU, Memory, and Disk I/O metrics
      process:
        # include:
        #   match_type: regexp
        #   names:
        #     - ".*[dD]uo.*"
        #     - ".*[cC]ode.*"
        #     - ".*[sS]plunk.*"
        mute_process_name_error: true
        mute_process_user_error: true
        mute_process_io_error: true
        mute_process_exe_error: true

exporters:
  # prometheus:
  #   endpoint: "0.0.0.0:9464"
  signalfx:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    realm: ${SPLUNK_REALM}
    # ingest_url: ${SPLUNK_INGEST_URL} 
    # trace_url: ${SPLUNK_TRACE_URL} 
    # api_url: ${SPLUNK_API_URL}

processors:
  resource/splunk_at_splunk: # Adds attributes to metrics
    attributes:
      - action: insert
        key: hardware
        value: physical
      - action: insert
        key: splunkit/team
        value: ${SPLUNK_TEAM}
      - action: insert
        key: splunkit/resource
        value: ${RESOURCE_TYPE}
  batch:
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true

extensions:
  health_check:
  # healthcheckv2:
  #   use_v2: true
  pprof:
  zpages:

service:
  extensions:
    - health_check
    - pprof
    - zpages
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch, resourcedetection, resource/splunk_at_splunk]
      exporters: [signalfx]
